# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-27 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neigbourhood',
            old_name='dscription',
            new_name='description',
        ),
    ]
