# Generated by Django 2.2.6 on 2019-12-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='hood',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hood',
            new_name='neighbourhood',
        ),
    ]
